
name: Publish

on:
  release:
    types:
      - released

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm -r --filter='./{plugins,packages}/*' publish
        env:
          NODE_AUTH_TOKEN: $${{ secrets.NPM_TOKEN }}
      - uses: softprops/action-gh-release@v2
        with:
          files: pnpm-lock.yaml

  factorio:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm -r --filter='./{plugins,packages}/*' run build-mod --output-dir ../../dist
      - run: node ./publish.js factorio ./dist
        env:
          FACTORIO_TOKEN: ${{ secrets.FACTORIO_TOKEN }}
      - uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
